# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-19 12:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Idc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('address', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254, verbose_name='email address of the IDC')),
                ('letter', models.CharField(max_length=5)),
            ],
            options={
                'db_table': 'resources_idc',
            },
        ),
    ]
