# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-23 06:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cabinet', '0001_initial'),
        ('manufacturer', '0001_initial'),
        ('idcs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_addr', models.CharField(db_index=True, help_text='ip addr', max_length=15, unique=True, verbose_name='ip addr')),
                ('netmask', models.CharField(help_text='netmask', max_length=15, verbose_name='subnet_mask')),
                ('remark', models.CharField(help_text='remarks', max_length=200, null=True, verbose_name='remarks')),
            ],
            options={
                'ordering': ['id'],
                'db_table': 'resource_ip',
            },
        ),
        migrations.CreateModel(
            name='NetworkDevice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='NIC name', max_length=20, verbose_name='NIC name')),
                ('mac_address', models.CharField(help_text='MAC address', max_length=30, verbose_name='MAC_address')),
                ('remark', models.CharField(help_text='remarks', max_length=200, verbose_name='remarks')),
            ],
            options={
                'ordering': ['id'],
                'db_table': 'resource_network_device',
            },
        ),
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(db_index=True, help_text='IP', max_length=15, unique=True)),
                ('hostname', models.CharField(db_index=True, help_text='hostname', max_length=20, unique=True)),
                ('cpu', models.CharField(help_text='CPU', max_length=50)),
                ('mem', models.CharField(help_text='memory', max_length=32)),
                ('disk', models.CharField(help_text='disk', max_length=200, verbose_name='disk')),
                ('os', models.CharField(help_text='OS', max_length=50, verbose_name='OS')),
                ('sn', models.CharField(db_index=True, help_text='SN', max_length=50, verbose_name='sn')),
                ('rmt_card_ip', models.CharField(db_index=True, help_text='ip of the remote manage card', max_length=15, unique=True, verbose_name='rm_card_ip')),
                ('cabinet_position', models.CharField(help_text='cabinet position', max_length=20, verbose_name='the position in the cabinet')),
                ('uuid', models.CharField(db_index=True, help_text='UUID', max_length=30, unique=True, verbose_name='UUID')),
                ('last_check', models.DateTimeField(auto_now=True, db_index=True, help_text='last check time', verbose_name='last_check_time')),
                ('cabinet', models.ForeignKey(help_text='cabinet located in', null=True, on_delete=django.db.models.deletion.CASCADE, to='cabinet.Cabinet', verbose_name='cabinet located in')),
                ('idc', models.ForeignKey(help_text='house located in', null=True, on_delete=django.db.models.deletion.CASCADE, to='idcs.Idc', verbose_name='house located in')),
                ('manufacturer', models.ForeignKey(help_text='manufacturer', on_delete=django.db.models.deletion.CASCADE, to='manufacturer.Manufacturer', verbose_name='manufacturer')),
                ('model_name', models.ForeignKey(help_text='server model', on_delete=django.db.models.deletion.CASCADE, to='manufacturer.ProductModel', verbose_name='server model')),
            ],
            options={
                'ordering': ['id'],
                'db_table': 'resource_servers',
            },
        ),
        migrations.AddField(
            model_name='networkdevice',
            name='host',
            field=models.ForeignKey(help_text='server located in', on_delete=django.db.models.deletion.CASCADE, to='servers.Server', verbose_name='server located in'),
        ),
        migrations.AddField(
            model_name='ip',
            name='device',
            field=models.ForeignKey(help_text='NIC located in', on_delete=django.db.models.deletion.CASCADE, to='servers.NetworkDevice', verbose_name='NIC located in'),
        ),
    ]
